### ISSUE TITLE
oc dry-run doesn't always catch issues

### ISSUE THREAD

**Issue by ghost** [cloudigrade/shiftigrade#15]
We pipe our templates to `oc apply --dry-run -f -` to verify that they are valid, but I believe since they are not actually being sent to the server and verified there that we are only passing client side validation. This unfortunately has the side effect of making it seem like our templates are sound (https://travis-ci.org/cloudigrade/shiftigrade/builds/395145967?utm_source=github_status&utm_medium=notification) when they are not (https://travis-ci.org/cloudigrade/shiftigrade/builds/395151169?utm_source=github_status&utm_medium=notification)

Perhaps we should replace using dry-run with creating a one off namespace, creating the objects, and then nuking said namespace?

**Comment by kdelee** [comment]
if possible to avoid actually spinning up stuff....make `replicaCount` configurable? i.e. 0?

**Comment by ghost** [comment]
That's a good idea, although regardless we'd never actually wait for it to complete, nuking the namespace as soon as we got a 👍 from the apply.

**Comment by elyezer** [comment]
This and https://github.com/cloudigrade/shiftigrade/issues/10 are related in the sense of allowing specifying the project (namespace) to create the objects. Maybe we should extract the project configuration into a new issue and make this and #10 depend on it?
